name: CI/CD Localhost

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Deploy to localhost
        run: npm run
